### PR TITLE
gzip: fix memory allocs (buffers not returned to pool)

### LINKED ISSUE #8: dictFlatePool not helping much (lots of new flate compressor allocations)
Here is a snippet of alloc_space heap profile for program using pgzip to write ~770MB file:

```
> go tool pprof -alloc_space PROG mem.prof
Entering interactive mode (type "help" for commands)
(pprof) top20
66762.39MB of 67431.14MB total (99.01%)
Dropped 55 nodes (cum <= 337.16MB)
Showing top 20 nodes out of 41 (cum >= 12452.37MB)
      flat  flat%   sum%        cum   cum%
17734.77MB 26.30% 26.30% 17734.77MB 26.30%  compress/flate.(*compressor).init
...
 3473.48MB  5.15% 81.09%  3473.48MB  5.15%  github.com/.../vendor/github.com/klauspost/pgzip.(*Writer).compressCurrent
...
 2757.36MB  4.09% 89.66% 20834.23MB 30.90%  github.com/.../vendor/github.com/klauspost/pgzip.compressBlock
```

During compression, memory usage of program grows by ~5GB. With regular gzip, memory usage is constant during compression.

Am I reading this right that `dictFlatePool` is not helping as it should? Shouldn't the number of compressors be limited by the number of blocks?

### PR DESCRIPTION
**Pull request by wojas**
Fix allocation leaks during gzip writes. Due to incorrect use of the dstPool (unmatched Get and Put), large amounts of memory were temporarily allocated during writes and not put back into the pool.

This also removes some special handling code in compressCurrent that would recursively call itself for too large input buffers. This condition can never occur, because Write ensures that blocks are capped
and there is no other public interface that extends currentBuffer. The recursive call that slices the buffer would have made returning byte slices to the Pool dangerous, as we could have been returning the same
underlying buffer multiple times.

This also adds a test to check allocations per Write to prevent regressions. There is further room for improvement, but this was by far the biggest leak.

Closes #8 

~~Additionally, this adds a go.mod for Go modules support.~~

(Note that tests broke with recent commit  a8ba21498dc99e88bfc7677aa9b3ef38ef0101cc).

### CODE REVIEW

**Comment by klauspost** [comment]
Thanks. I will review tomorrow.

Please take out the go.mod - I have not decided to go that route yet.

**Comment by wojas** [comment]
Thanks for the fast response. I took out the `go.mod`.

**Comment by wojas** [comment]
I found that the tests pass without `-v`, but fail with `-v`... Investigating.

**Comment by wojas** [comment]
This PR should be done as is. The remaining test failures are also present in master and I cannot reproduce them locally in my branch, which is based on v1.2.1. 

I suspect they are caused by a8ba21498dc99e88bfc7677aa9b3ef38ef0101cc.

**Comment by klauspost** [comment]
Thanks! I'll take a look. 👍

File: gzip_norace_test.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+
+	// Locally it still allocates 660 bytes, which can probably be further reduced,
+	// but it's better than the 175846 bytes before the pool release fix this tests.
+	// TODO: Further reduce allocations
+	if allocBytes > 10240 {
+		t.Errorf("Write allocated too much memory per run (%.0f bytes), Pool used incorrectly?", allocBytes)
+	}
+}
+
+// AllocBytesPerRUn returns the average total size of allocations during calls to f.
```
Comment (klauspost) [inline gzip_norace_test.go]:
```suggestion
// allocBytesPerRun returns the average total size of allocations during calls to f.
```

File: gzip_norace_test.go [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+// To compute the number of allocations, the function will first be run once as
+// a warm-up. The average total size of allocations over the specified number of
+// runs will then be measured and returned.
+//
+// AllocBytesPerRun sets GOMAXPROCS to 1 during its measurement and will restore
+// it before returning.
+//
+// This function is based on testing.AllocsPerRun, which counts the number of
+// allocations instead of the total size of them in bytes.
+func AllocBytesPerRun(runs int, f func()) (avg float64) {
```
Comment (klauspost) [inline gzip_norace_test.go]:
```suggestion
func allocBytesPerRun(runs int, f func()) (avg float64) {
```

File: gzip_norace_test.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+	allocBytes := AllocBytesPerRun(1000, func() {
+		_, _ = w.Write(data)
+	})
+	t.Logf("Allocated %.0f bytes per Write on average", allocBytes)
+
+	// Locally it still allocates 660 bytes, which can probably be further reduced,
+	// but it's better than the 175846 bytes before the pool release fix this tests.
+	// TODO: Further reduce allocations
+	if allocBytes > 10240 {
+		t.Errorf("Write allocated too much memory per run (%.0f bytes), Pool used incorrectly?", allocBytes)
```
Comment (klauspost) [inline gzip_norace_test.go]: For the failures it reports `gzip_test.go:637: Write allocated too much memory per run (18446744073709436 bytes), Pool used incorrectly?`

That is 18446.7TB - I think you would be hard pressed to allocated that much, so I suspect there is something wrong.

File: gzip_norace_test.go [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+	oldTotal := memstats.TotalAlloc
+
+	// Run the function the specified number of times
+	for i := 0; i < runs; i++ {
+		f()
+	}
+
+	// Read the final statistics
+	runtime.ReadMemStats(&memstats)
+	allocs := memstats.TotalAlloc - oldTotal
```
Comment (klauspost) [inline gzip_norace_test.go]: I suspect the error is caused by `memstats.TotalAlloc > oldTotal` causing an underflow and the crazy numbers.

Not really an expert on how that can happen.

File: gzip_unreliable_test.go [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+
+// Test that the panics catch unsafe concurrent writing (a panic is better than data corruption)
+// This test is UNRELIABLE and slow. The more concurrency (GOMAXPROCS), the more likely
+// a race condition will be hit. If GOMAXPROCS=1, the condition is never hit.
+func TestConcurrentRacePanic(t *testing.T) {
+	w := NewWriter(SlowDiscard(2 * time.Millisecond))
+	w.SetConcurrency(1000, 1)
+	data := bytes.Repeat([]byte("T"), 100000) // varying block splits
+
+	const n = 1000
```
Comment (klauspost) [inline gzip_unreliable_test.go]: Maybe:
```suggestion
	n := 1000
	if testing.Short() {
		n = 10
	}
```

(or make the `i++` change to bigger increments).

Though you have this guarded nicely by tags.

File: gzip_norace_test.go (hunk 3 above)
Comment (wojas) [reply gzip_norace_test.go]: Are you sure this happened with the latest version? I noticed this in earlier test runs and 799eba1c20806ffaa5c2a8ec998ba1d062e9f062 fixes this. Before that commit I was using `.Alloc` instead of `.TotalAlloc`.

From the `MemStats` comments:

> TotalAlloc increases as heap objects are allocated, but unlike Alloc and HeapAlloc, it does not decrease when objects are freed.

File: gzip_unreliable_test.go (hunk 5 above)
Comment (wojas) [reply gzip_unreliable_test.go]: This test tries to reproduce a race condition. I tried, but I cannot reproduce it with `n = 10`.

File: gzip_norace_test.go (hunk 4 above)
Comment (wojas) [reply gzip_norace_test.go]: See previous comment

File: gzip_norace_test.go (hunk 3 above)
Comment (klauspost) [reply gzip_norace_test.go]: Yeah, seems I mixed up the runs. Anyway, merging master should fix the writer.

File: gzip_unreliable_test.go (hunk 5 above)
Comment (klauspost) [reply gzip_unreliable_test.go]: ah, ok, no problem.

**Comment by klauspost** [comment]
Cool. I will give it some tests before the next release. Thanks a bunch!
