### PR TITLE
fix: return currentBuffer and prevTail to dstPool in init to stop leak

### LINKED ISSUE #56: buf leak in (*Writer).Close()
I use a writer in a loop, which looks like this:

`
z := gzip.NewWriter(nil)
for {
  buf := new(bytes.Buffer)
  z.Reset(buf)
  msg := getMessage()
  z.Write(msg)
  z.Close()
  processMessage(msg)
}    
`

When closing z, `Close()` calls `compressCurrent()`, which gets two buffers from z.dstPool. The second one, in gzip.go:272, is never put back to z.dstPool, since z.init (called from z.Reset) sets `z.currentBuffer = nil`.

It means that dstPool is not fully utilized, and there are many redundant alllcations

### PR DESCRIPTION
**Pull request by SAY-5**
## What

Fixes #56.

`Writer.init` unconditionally cleared `z.currentBuffer` and `z.prevTail` to `nil`. On a `Reset` / `Close` cycle that dropped a fully-allocated buffer (and an optional tail buffer) on the floor every iteration: both had just been fetched from `z.dstPool` on the preceding `Close` path (`compressCurrent` at gzip.go:272, `Close` calling `compressCurrent` with `flush=true`), so the pool never saw them again.

Long-running hot loops that reuse a single Writer with `Reset(buf); Write; Close; ...` grew allocations without bound as the sync.Pool hit-rate collapsed.

## Fix

Put both buffers back before zeroing them. The existing `// Put in .compressBlock` and `Put p / Put prevTail` call sites (lines 272, 397, 441, 458) show the pattern already in use for the other `Get` locations - this change just extends it to the init path so the pool is complete.

## Behaviour

- `NewWriter` → `init` on a fresh `*Writer`: both fields are zero-value `nil`, the new guards short-circuit, nothing changes.
- `Reset` → `SetConcurrency` → `init` after a `Close`: both fields hold live pool buffers, they are returned, and the pool stays healthy.

## Verification

Locally on macOS, go 1.26.2:
- `gofmt -s -l`: clean
- `go vet ./...`: clean
- `go test -race -count=1 ./...`: pass (full suite, ~130s under -race)

Closes #56

### CODE REVIEW

**Review by klauspost — APPROVED** [review]
lgtm

File: gzip.go [hunk 1]
```diff
@@ -155,9 +155,19 @@ func (z *Writer) init(w io.Writer, level int) {
 	z.Extra = nil
 	z.ModTime = time.Time{}
 	z.wroteHeader = false
-	z.currentBuffer = nil
+	// Return any live buffer back to the pool before clearing it so
+	// repeated NewWriter/Close cycles via init(...) stop leaking one
+	// dstPool slot per iteration (#56). Same for prevTail, which init
+	// used to drop on the floor.
```
Comment (klauspost) [inline gzip.go]:
```suggestion
```
